# Generated by Django 4.1.4 on 2022-12-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('is_lucid', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
        ),
    ]
