# Generated by Django 4.1.4 on 2022-12-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucid_diary', '0002_note_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='user',
        ),
    ]
